apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: static-web-dev
  namespace: student51-static-dev
spec:
  rules:
  - host: dev.opsta.net
    http:
      paths:
      - path: /student51/static(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: static-web-dev
            port:
              number: 80
