apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-dev
  namespace: student51-static-dev
  labels:
    app: static-web-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-web-dev
  template:
    metadata:
      labels:
        app: static-web-dev
    spec:
      containers:
      - name: static-web-de
        image: ghcr.io/boatprakit/static-web:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      imagePullSecrets:
      - name: registry-github
